- url: "https://github.com/tushar2704/VibeCode"
  owner: "tushar2704"
  name: "VibeCode"
  dev_owner_name: "Tushar Kumar"
  team: "Demo"

- url: "https://github.com/KesetebirhanDelele/RepoPulse"
  owner: "KesetebirhanDelele"
  name: "RepoPulse"
  dev_owner_name: "Kesetebirhan Delele"
  team: "Core"

- url: "https://github.com/Nikhil9490/LeetCode"
  owner: "Nikhil9490"
  name: "LeetCode"
  dev_owner_name: "Nikhil Kumar"
  team: "Core"

- url: "https://github.com/psf/requests"
  owner: "psf"
  name: "requests"
  dev_owner_name: "PSF"
  team: "Demo-OSS"

- url: "https://github.com/tiangolo/fastapi"
  owner: "tiangolo"
  name: "fastapi"
  dev_owner_name: "FastAPI Maintainers"
  team: "Demo-API"

- url: "https://github.com/pallets/flask"
  owner: "pallets"
  name: "flask"
  dev_owner_name: "Pallets Team"
  team: "Demo-Web"

- url: "https://github.com/facebook/react"
  owner: "facebook"
  name: "react"
  dev_owner_name: "Meta OSS"
  team: "Demo-Frontend"

- url: "https://github.com/kubernetes/kubernetes"
  owner: "kubernetes"
  name: "kubernetes"
  dev_owner_name: "Kubernetes SIGs"
  team: "Demo-Platform" 