- url: "https://github.com/tushar2704/VibeCode"
  owner: "tushar2704"
  name: "VibeCode"
  dev_owner_name: "Tushar Kumar"
  team: "Demo"

- url: "https://github.com/KesetebirhanDelele/RepoPulse"
  owner: "KesetebirhanDelele"
  name: "RepoPulse"
  dev_owner_name: "Kesetebirhan Delele"
  team: "Core"

- url: "https://github.com/Nikhil9490/LeetCode"
  owner: "Nikhil9490"
  name: "LeetCode"
  dev_owner_name: "Nikhil Kumar"
  team: "Core"